language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
install:
  - cat composer.json
  - composer install
  - mkdir -p ./data
  - wget -O data/eu-lotl.xml https://ec.europa.eu/tools/lotl/eu-lotl.xml
  - scripts/showtests.sh
