language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
install:
  - composer config -g github-oauth.github.com "$GITHUB_API_KEY"
  - cat composer.json
  - composer install
  # - bash -c tools/get-tls.sh
  - scripts/showtests.sh
cache:
  directories:
    - $HOME/.composer/cache/files
    # - $HOME/data/tl
