language: php
php:
  # - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
install:
  - rm composer.lock
  - cat composer.json
  - composer install
  - mkdir -p ./data
  - wget -O data/tlol.xml https://ec.europa.eu/information_society/policy/esignature/trusted-list/tl-mp.xml
  - scripts/showtests.sh
